### ISSUE TITLE
Technical design

### ISSUE THREAD

**Issue by ghost** [pierreradas/jammming#11]
> In order to let the app listen to key presses, we will let the rendered “search” button to have a new property “onkeypress” that would call a new event function called eventFuction(e).

`eventFunction` is a poor name for a function, it's possible this will cause confusion for other programmers reading or maintaining your code.

> The eventFunction would check whether the key pressed is Enter (e.keycode === 13), and then call the search method of the class.

This is fine... it definitely works. But it's not a scaleable solution to something as simple as submitting a form.

As your app expands and you add more and more forms, will you always add two event listeners to each form? One so that you can click the submit button and another so that you can press enter to submit? For a simple website or app with a few forms... You might end up dedicating a large chunk of your codebase just to "form submission" logic.

You may want to research a simpler, HTML-based solution. Just change the `div` element to a `form` element and change the `a` element to an `input` element with `type="submit"`. This gives you the same result, and reduces the amount of duplicate JavaScript you'll need to write. Just write a single `onSubmit` listener and handler for each form.

**Comment by pierreradas** [comment]
Great comment, thank you
