### ISSUE TITLE
Spotify module

### ISSUE THREAD

**Issue by ghost** [pierreradas/jammming#2]
There are a few issues in your Spotify module that keep you from being able to save playlists (resulting in that alert box reading "there was an issue with your request: 404").

https://github.com/pierreradas/jammming/blob/master/src/util/Spotify.js#L81-L94

First, for your `.then()` to have a useful `response`, you'll need to first `await` the response from the `fetch`. Add an `await` (or even `return`) keyword on line 81 and you'll get the proper response status and payload.

https://github.com/pierreradas/jammming/blob/master/src/util/Spotify.js#L90

You're also not properly saving the playlist with its specified playlistName. Replace 'test' here with `playlistName` to fix this.

**Comment by pierreradas** [comment]
Done, working.
