### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by ghost** [pierreradas/jammming#8]
Satisfactory

Your app works pretty well for the most part, good job! Searching for tracks and adding them to a playlist works quite easily.

Make sure to make the necessary changes to your Spotify module so that the save playlists feature works properly.

**Comment by pierreradas** [comment]
I made an improvement that makes the app working well. The save functonnality now works great.

I took into consideration your other comments which are of great help to understand best practices and how to improve my coding abilities.
